[package]
name = "outliner"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
base64 = "0.22.1"
clap = { version = "4.6.1", features = ["derive"] }
futures-util = "0.3.31"
qpdf = "0.3.5"
regex = "1.12.2"
rig-core = "0.36.0"
schemars = { version = "1.2.1", features = ["derive"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
shellexpand = "3.1.2"
tempfile = "3.23.0"
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread"] }
toml = "0.8.23"
tracing = "0.1.44"
tracing-indicatif = "0.3.9"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
